version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  db-migration:
    build:
      context: .
      dockerfile: PracticeAssessment.Migration/Dockerfile
    environment:
      - DATABASE_CONNECTION=Data Source=db;Initial Catalog=Practice;User Id=sa;Password=123456;TrustServerCertificate=true;
    depends_on:
      - db

  webapi:
    build:
      context: .
      dockerfile: PracticeAssessment/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CONNECTION=Data Source=db;Initial Catalog=Practice;User Id=sa;Password=123456;TrustServerCertificate=true;
    ports:
      - "80:80"
    depends_on:
      - db-migration